# Generated by Django 4.1.1 on 2022-10-05 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddFeeling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('feelings', models.CharField(choices=[('happy', 'Happy'), ('excited', 'Excited'), ('calm', 'Calm'), ('disppointed', 'Disppointed'), ('anxious', 'Anxious'), ('angry', 'Angry')], max_length=15, null=True)),
                ('details', models.TextField(null=True)),
            ],
        ),
    ]
