# Generated by Django 4.1.1 on 2022-10-09 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_userprofile_user'),
        ('recordemo', '0002_addfeeling_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addfeeling',
            name='user',
        ),
        migrations.AddField(
            model_name='addfeeling',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_feelings', to='profiles.userprofile'),
        ),
    ]
