# Generated by Django 4.1.1 on 2022-12-17 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordemo', '0003_remove_addfeeling_user_addfeeling_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addfeeling',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
