# Generated by Django 4.1.1 on 2022-12-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordemo', '0004_alter_addfeeling_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addfeeling',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
