# Generated by Django 4.1.1 on 2022-12-18 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordemo', '0005_alter_addfeeling_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='addfeeling',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
